### PR TITLE
fix C label to Nest

### PR DESCRIPTION
**Pull request by dienhoa**
Fix wrong label 'C' to correct one 'Ne'

### CODE REVIEW

**Comment by radekosmulski** [comment]
Thank you very much Dien Hoa for this PR! 🙂Could I please ask you what changes you are suggesting and why? I tried looking through the diff but since its json from an NB it was a little bit hard. 

I am not sure I am reading this right, but as far as I can tell label 'C' does not exist in the datest?

Thanks again for the PR and if you wouldn't mind sharing a few words of explanation that would be awesome! 🙂

**Comment by dienhoa** [comment]
I detail the PR in the fastai forum. Sorry for missing information here, I will be more careful next time. Actually, there are 2 labels which are 'Ne' but are wrongly labeled as 'C'. I've just added call_type[869] = 'Ne'; call_type[1663] = 'Ne' at one cell to fix it.

**Comment by radekosmulski** [comment]
No worries at all, will check on the fast.ai forums, thank you for the heads up! BTW I think this was an issue with an earlier version of the notebook, I am not seeing calls with C labels anywhere now, but will check on the fast.ai forums to make sure I understand the issue.

Thanks again for the PR and for your explanation! 🙂

**Comment by dienhoa** [comment]
This problem is fixed from the master branch

**Pull request closed without merging**
